"""add resumes.indexing_status

Revision ID: 050bb192dd0a
Revises: 46594543b6d0
Create Date: 2026-08-07 23:08:10.774381

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '050bb192dd0a'
down_revision: str | None = '46594543b6d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('indexing_status', sa.Text(), server_default='pending', nullable=False))
    op.add_column('resumes', sa.Column('indexing_error', sa.Text(), nullable=True))
    op.create_check_constraint('ck_resumes_indexing_status', 'resumes', "indexing_status IN ('pending', 'processing', 'ready', 'failed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_resumes_indexing_status', 'resumes', type_='check')
    op.drop_column('resumes', 'indexing_error')
    op.drop_column('resumes', 'indexing_status')
    # ### end Alembic commands ###
