"""add companies.news_last_queried_at

Revision ID: 46594543b6d0
Revises: 0001_initial
Create Date: 2026-08-07 20:35:10.116198

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '46594543b6d0'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('news_last_queried_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'news_last_queried_at')
    # ### end Alembic commands ###
